### Update port to match .env file or controller file.
### Request 1: Create an artwork
POST http://localhost:3002/arts HTTP/1.1
content-type: application/json

{
    "imgurl": "https://drive.google.com/uc?export=view&id=1b8ICBjwmRBvXwrzl59FlcJHSJIW9e6lX",
    "title": "Valley Heat 2",
    "width": 9,
    "height": 6,
    "depth": 0.1,
    "genre": "landscape",
    "media": "watercolor",
    "date": "2023-05-01",
    "descr": "Just a quick landscape watercolor of the heat of the day."
}

### Request 2: Create another artwork
POST http://localhost:3002/arts HTTP/1.1
content-type: application/json

{
    "imgurl": "images/valley-morning-12.jpg",
    "title": "Valley Morning 12",
    "width": 8,
    "height": 8,
    "depth": 0.25,
    "genre": "landscape",
    "media": "oil on board",
    "date": "2023-03-10",
    "descr": "Just a quick landscape in oil paint."

}

### Request 3: Create an artwork
POST http://localhost:3002/arts HTTP/1.1
content-type: application/json

{
    "imgurl": "images/pvl-valley-morning-63.jpg",
    "title": "Valley Morning 63",
    "width": 9,
    "height": 6,
    "depth": null,
    "genre": "landscape",
    "media": "watercolor on archival paper",
    "date": "2023-01-12",
    "descr": "I have painted more than 63 images of the Willamette Valley in the morning."

}

### Request 4: Create another artwork
POST http://localhost:3002/arts HTTP/1.1
content-type: application/json

{
    "imgurl": "https://drive.google.com/uc?export=view&id=0-sWSFgJLFY0D7Y4hJ4x6CSg",
    "title": "Canyon Dreams 36",
    "width": 8,
    "height": 8,
    "depth": 0.25,
    "genre": "landscape",
    "media": "oil",
    "date": "2015-01-26",
    "descr": "I love the southwest and its canyons. I dream of the red cliffs."
}


### Request 5: Retrieve should return the 4 artworks.
GET http://localhost:3002/arts HTTP/1.1
content-type: application/json


### Request 6: UPDATE the last one.
PUT http://localhost:3002/arts/64d6666e0333ff0d151b7a14 HTTP/1.1
content-type: application/json

{
    "imgurl": "images/valley-morning12.jpg",
    "title": "Valley Morning 12",
    "width": 8,
    "height": 8,
    "depth": 0.25,
    "genre": "landscape",
    "media": "oil",
    "date": "2023-08-11",
    "descr": "another valley morning painting, in oil."
}

### Request 7: Verify that the previous update worked
GET http://localhost:3002/arts/64d66548d44d6efb60874d9e HTTP/1.1



### Request 20: Delete for non-existent ID. 404 status code
DELETE http://localhost:3002/arts/64d66548d44d6efb60874d9e HTTP/1.1
